theme = "zafta"
baseurl = "http://allunicode.info"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
uglyurls = true
disableSitemap = true
disableRSS = true
languageCode = "en-us"
title = "All Unicode Characters"
MetaDataFormat = "toml"
ignoreFiles = [ "~$" ]
[author]
    name = "Ted Mielczarek"
[permalinks]
  c = "/c/:filename"
